In [43]:
import pandas as pd

In [44]:
# Create a dataset with 200 rows for datetime practice
df = pd.DataFrame({
    'date_created': pd.date_range('2023-01-01', periods=200, freq='D'),
    'date_modified': pd.date_range('2023-06-20', periods=200, freq='12h'),
    'value': range(1, 201),
    'category': ['A', 'B', 'C', 'D'] * 50
})

print(df.info())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date_created   200 non-null    datetime64[us]
 1   date_modified  200 non-null    datetime64[us]
 2   value          200 non-null    int64
 3   category       200 non-null    str
dtypes: datetime64[us](2), int64(1), str(1)
memory usage: 6.4 KB
None

  date_created       date_modified  value category
0   2023-01-01 2023-06-20 00:00:00      1        A
1   2023-01-02 2023-06-20 12:00:00      2        B
2   2023-01-03 2023-06-21 00:00:00      3        C
3   2023-01-04 2023-06-21 12:00:00      4        D
4   2023-01-05 2023-06-22 00:00:00      5        A

In [45]:
# convert datetime into strings
df['date_created'].dt.strftime('%d-%m-%Y')

0      01-01-2023
1      02-01-2023
2      03-01-2023
3      04-01-2023
4      05-01-2023
          ...
195    15-07-2023
196    16-07-2023
197    17-07-2023
198    18-07-2023
199    19-07-2023
Name: date_created, Length: 200, dtype: str

In [46]:
dt_accessor = df["date_created"].dt
dt_accessor.year
dt_accessor.month
dt_accessor.day
dt_accessor.day_of_week >= 5

0       True
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197    False
198    False
199    False
Name: date_created, Length: 200, dtype: bool

In [47]:
# extract date and time components
dt_accessor.time
dt_accessor.date

0      2023-01-01
1      2023-01-02
2      2023-01-03
3      2023-01-04
4      2023-01-05
          ...
195    2023-07-15
196    2023-07-16
197    2023-07-17
198    2023-07-18
199    2023-07-19
Name: date_created, Length: 200, dtype: object

In [48]:
dt_accessor.quarter.astype("str") + "Q " + dt_accessor.year.astype("str")

0      1Q 2023
1      1Q 2023
2      1Q 2023
3      1Q 2023
4      1Q 2023
        ...
195    3Q 2023
196    3Q 2023
197    3Q 2023
198    3Q 2023
199    3Q 2023
Name: date_created, Length: 200, dtype: str

In [49]:
df["date_created"] + pd.Timedelta("7 days") + pd.Timedelta("2 hours") + pd.Timedelta("30 minutes") + pd.Timedelta("15 seconds")

0     2023-01-08 02:30:15
1     2023-01-09 02:30:15
2     2023-01-10 02:30:15
3     2023-01-11 02:30:15
4     2023-01-12 02:30:15
              ...
195   2023-07-22 02:30:15
196   2023-07-23 02:30:15
197   2023-07-24 02:30:15
198   2023-07-25 02:30:15
199   2023-07-26 02:30:15
Name: date_created, Length: 200, dtype: datetime64[us]

In [50]:
pd.date_range(start="2024-01-01", end="2024-12-31", freq="h")

# month-end anchored (12 months)
pd.date_range(start="2024-01-31", periods=12, freq="ME")

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[us]', freq='ME')

In [52]:
# Add a datetime string column and inject missing values
df["datetime_miss"] = df["date_modified"].dt.strftime("%Y-%m-%d %H:%M:%S")
df.loc[df.index % 7 == 0, "datetime_miss"] = pd.NA
df

    date_created       date_modified  value category        datetime_miss
0     2023-01-01 2023-06-20 00:00:00      1        A                  NaN
1     2023-01-02 2023-06-20 12:00:00      2        B  2023-06-20 12:00:00
2     2023-01-03 2023-06-21 00:00:00      3        C  2023-06-21 00:00:00
3     2023-01-04 2023-06-21 12:00:00      4        D  2023-06-21 12:00:00
4     2023-01-05 2023-06-22 00:00:00      5        A  2023-06-22 00:00:00
..           ...                 ...    ...      ...                  ...
195   2023-07-15 2023-09-25 12:00:00    196        D  2023-09-25 12:00:00
196   2023-07-16 2023-09-26 00:00:00    197        A                  NaN
197   2023-07-17 2023-09-26 12:00:00    198        B  2023-09-26 12:00:00
198   2023-07-18 2023-09-27 00:00:00    199        C  2023-09-27 00:00:00
199   2023-07-19 2023-09-27 12:00:00    200        D  2023-09-27 12:00:00

[200 rows x 5 columns]

In [54]:
df["datetime_miss"] = pd.to_datetime(df["datetime_miss"])
df

    date_created       date_modified  value category       datetime_miss
0     2023-01-01 2023-06-20 00:00:00      1        A                 NaT
1     2023-01-02 2023-06-20 12:00:00      2        B 2023-06-20 12:00:00
2     2023-01-03 2023-06-21 00:00:00      3        C 2023-06-21 00:00:00
3     2023-01-04 2023-06-21 12:00:00      4        D 2023-06-21 12:00:00
4     2023-01-05 2023-06-22 00:00:00      5        A 2023-06-22 00:00:00
..           ...                 ...    ...      ...                 ...
195   2023-07-15 2023-09-25 12:00:00    196        D 2023-09-25 12:00:00
196   2023-07-16 2023-09-26 00:00:00    197        A                 NaT
197   2023-07-17 2023-09-26 12:00:00    198        B 2023-09-26 12:00:00
198   2023-07-18 2023-09-27 00:00:00    199        C 2023-09-27 00:00:00
199   2023-07-19 2023-09-27 12:00:00    200        D 2023-09-27 12:00:00

[200 rows x 5 columns]

In [58]:
df["datetime_miss"].bfill() # bfill fills with the last observed value (backward fill)
df["datetime_miss"].ffill() # ffill fills with the next observed value (forward fill)

# limit to at most N consecutive gaps filled
df["datetime_miss"].ffill(limit=3)

# combined: ffill first, then bfill for any leading NaN
df["datetime_miss"].ffill().bfill()

0     2023-06-20 12:00:00
1     2023-06-20 12:00:00
2     2023-06-21 00:00:00
3     2023-06-21 12:00:00
4     2023-06-22 00:00:00
              ...
195   2023-09-25 12:00:00
196   2023-09-25 12:00:00
197   2023-09-26 12:00:00
198   2023-09-27 00:00:00
199   2023-09-27 12:00:00
Name: datetime_miss, Length: 200, dtype: datetime64[us]

In [ ]:
pd.Timestamp("2024-01-01 00:00:00")
pd.to_datetime("2024-01-01 00:00:00")

Timestamp('2024-01-01 00:00:00')

In [ ]:
# filling missing values with a specific value
df["datetime_miss"].fillna(pd.to_datetime("2024-01-01 00:00:00"))

# with the most repeated value
df["datetime_miss"].fillna(df["datetime_miss"].mode()[0])

0     2023-06-20 12:00:00
1     2023-06-20 12:00:00
2     2023-06-21 00:00:00
3     2023-06-21 12:00:00
4     2023-06-22 00:00:00
              ...
195   2023-09-25 12:00:00
196   2023-06-20 12:00:00
197   2023-09-26 12:00:00
198   2023-09-27 00:00:00
199   2023-09-27 12:00:00
Name: datetime_miss, Length: 200, dtype: datetime64[us]

In [70]:
# fillna with interpolation
df["datetime_miss"].interpolate(method="linear")

0                     NaT
1     2023-06-20 12:00:00
2     2023-06-21 00:00:00
3     2023-06-21 12:00:00
4     2023-06-22 00:00:00
              ...
195   2023-09-25 12:00:00
196   2023-09-26 00:00:00
197   2023-09-26 12:00:00
198   2023-09-27 00:00:00
199   2023-09-27 12:00:00
Name: datetime_miss, Length: 200, dtype: datetime64[us]

In [75]:
df["date_shifted"] = df["date_created"].shift(2) # shift the values down by 2 rows
df["date_diff"] = df["date_created"].diff(1) # difference between the current and previous row
df

,date_created,date_modified,value,category,datetime_miss,date_shifted,date_diff
0,2023-01-01,2023-06-20 00:00:00,1,A,NaT,NaT,NaT
1,2023-01-02,2023-06-20 12:00:00,2,B,2023-06-20 12:00:00,NaT,1 days
2,2023-01-03,2023-06-21 00:00:00,3,C,2023-06-21 00:00:00,2023-01-01,1 days
3,2023-01-04,2023-06-21 12:00:00,4,D,2023-06-21 12:00:00,2023-01-02,1 days
4,2023-01-05,2023-06-22 00:00:00,5,A,2023-06-22 00:00:00,2023-01-03,1 days
...,...,...,...,...,...,...,...
195,2023-07-15,2023-09-25 12:00:00,196,D,2023-09-25 12:00:00,2023-07-13,1 days
196,2023-07-16,2023-09-26 00:00:00,197,A,NaT,2023-07-14,1 days
197,2023-07-17,2023-09-26 12:00:00,198,B,2023-09-26 12:00:00,2023-07-15,1 days
198,2023-07-18,2023-09-27 00:00:00,199,C,2023-09-27 00:00:00,2023-07-16,1 days
199,2023-07-19,2023-09-27 12:00:00,200,D,2023-09-27 12:00:00,2023-07-17,1 days

In [85]:
# rolling windows
df.value.rolling(window=7).mean() # 7-day rolling mean
df.value.rolling(window=30).sum() # 30-day rolling sum

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
        ...
195    5445.0
196    5475.0
197    5505.0
198    5535.0
199    5565.0
Name: value, Length: 200, dtype: float64

In [87]:
df["value"].expanding().sum() # expanding is similar to rolling, but it uses all previous values instead of a fixed window size

0          1.0
1          3.0
2          6.0
3         10.0
4         15.0
        ...
195    19306.0
196    19503.0
197    19701.0
198    19900.0
199    20100.0
Name: value, Length: 200, dtype: float64

In [93]:
# query
df[df["date_created"].dt.month == 1] # all rows where the month is January
df.query('date_created.dt.month == 1') # same as above, but using query method

df[(df["date_created"] > "2023-01-01") & (df["date_created"] < "2023-02-01")] # all rows where the date is in January 2023
df[df["date_created"].between("2023-01-01", "2023-02-01")] # same as above, but using between method
df.query('date_created.between("2023-01-01", "2023-02-01")') # same as above, but using query method

,date_created,date_modified,value,category,datetime_miss,date_shifted,date_diff
0,2023-01-01,2023-06-20 00:00:00,1,A,NaT,NaT,NaT
1,2023-01-02,2023-06-20 12:00:00,2,B,2023-06-20 12:00:00,NaT,1 days
2,2023-01-03,2023-06-21 00:00:00,3,C,2023-06-21 00:00:00,2023-01-01,1 days
3,2023-01-04,2023-06-21 12:00:00,4,D,2023-06-21 12:00:00,2023-01-02,1 days
4,2023-01-05,2023-06-22 00:00:00,5,A,2023-06-22 00:00:00,2023-01-03,1 days
5,2023-01-06,2023-06-22 12:00:00,6,B,2023-06-22 12:00:00,2023-01-04,1 days
6,2023-01-07,2023-06-23 00:00:00,7,C,2023-06-23 00:00:00,2023-01-05,1 days
7,2023-01-08,2023-06-23 12:00:00,8,D,NaT,2023-01-06,1 days
8,2023-01-09,2023-06-24 00:00:00,9,A,2023-06-24 00:00:00,2023-01-07,1 days
9,2023-01-10,2023-06-24 12:00:00,10,B,2023-06-24 12:00:00,2023-01-08,1 days
10,2023-01-11,2023-06-25 00:00:00,11,C,2023-06-25 00:00:00,2023-01-09,1 days
11,2023-01-12,2023-06-25 12:00:00,12,D,2023-06-25 12:00:00,2023-01-10,1 days
12,2023-01-13,2023-06-26 00:00:00,13,A,2023-06-26 00:00:00,2023-01-11,1 days
13,2023-01-14,2023-06-26 12:00:00,14,B,2023-06-26 12:00:00,2023-01-12,1 days
14,2023-01-15,2023-06-27 00:00:00,15,C,NaT,2023-01-13,1 days
15,2023-01-16,2023-06-27 12:00:00,16,D,2023-06-27 12:00:00,2023-01-14,1 days
16,2023-01-17,2023-06-28 00:00:00,17,A,2023-06-28 00:00:00,2023-01-15,1 days
17,2023-01-18,2023-06-28 12:00:00,18,B,2023-06-28 12:00:00,2023-01-16,1 days
18,2023-01-19,2023-06-29 00:00:00,19,C,2023-06-29 00:00:00,2023-01-17,1 days
19,2023-01-20,2023-06-29 12:00:00,20,D,2023-06-29 12:00:00,2023-01-18,1 days
20,2023-01-21,2023-06-30 00:00:00,21,A,2023-06-30 00:00:00,2023-01-19,1 days
21,2023-01-22,2023-06-30 12:00:00,22,B,NaT,2023-01-20,1 days
22,2023-01-23,2023-07-01 00:00:00,23,C,2023-07-01 00:00:00,2023-01-21,1 days
23,2023-01-24,2023-07-01 12:00:00,24,D,2023-07-01 12:00:00,2023-01-22,1 days
24,2023-01-25,2023-07-02 00:00:00,25,A,2023-07-02 00:00:00,2023-01-23,1 days
25,2023-01-26,2023-07-02 12:00:00,26,B,2023-07-02 12:00:00,2023-01-24,1 days
26,2023-01-27,2023-07-03 00:00:00,27,C,2023-07-03 00:00:00,2023-01-25,1 days
27,2023-01-28,2023-07-03 12:00:00,28,D,2023-07-03 12:00:00,2023-01-26,1 days
28,2023-01-29,2023-07-04 00:00:00,29,A,NaT,2023-01-27,1 days
29,2023-01-30,2023-07-04 12:00:00,30,B,2023-07-04 12:00:00,2023-01-28,1 days
30,2023-01-31,2023-07-05 00:00:00,31,C,2023-07-05 00:00:00,2023-01-29,1 days
31,2023-02-01,2023-07-05 12:00:00,32,D,2023-07-05 12:00:00,2023-01-30,1 days

In [ ]:
# use where, the difference is that where returns the original value if the condition is True, and NaN otherwise,
#  while query returns only the rows that satisfy the condition
df["date_created"].where(df["date_created"].dt.month == 1) # all rows where the month is January, NaN otherwise

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...
195          NaT
196          NaT
197          NaT
198          NaT
199          NaT
Name: date_created, Length: 200, dtype: datetime64[us]